rabbitmq:
  # url: "amqp://guest:guest@localhost:5672/" 
  url: "amqp://guest:guest@rabbitmq:5672/"
exchange:
  name: "clearsky.events.v1"
  type: "topic"
queue:
  name: "clearsky.orchestrator.events.v1"
  dlx: "clearsky.orchestrator.events.v1.dlq"
bindings:
  - "user.created"
